stages:
  - build

include:
  - local: 'ci/ci-template.yml'

variables:
  IMAGE_PREFIX: "$REGISTRY_USER"

build-frontend:
  extends: .build_template
  variables:
    IMAGE_NAME: "$IMAGE_PREFIX/frontend"
    DOCKER_BUILD_ARGS: "--build-arg REACT_APP_RAPIDAPI_KEY=$REACT_APP_RAPIDAPI_KEY --build-arg REACT_APP_GEOAPI_BASE_URL=$REACT_APP_GEOAPI_BASE_URL"
  only:
    refs:
      - main
    changes:
      - frontend/**/*

build-backend:
  extends: .build_template
  variables:
    IMAGE_NAME: "$IMAGE_PREFIX/backend"
  only:
    refs:
      - main
    changes:
      - backend/**/*

build-producer:
  extends: .build_template
  variables:
    IMAGE_NAME: "$IMAGE_PREFIX/producer"
  only:
    refs:
      - main
    changes:
      - producer/**/*

build-consumer:
  extends: .build_template
  variables:
    IMAGE_NAME: "$IMAGE_PREFIX/consumer"
  only:
    refs:
      - main
    changes:
      - consumer/**/*