apiVersion: v1
kind: Secret
metadata:
  name: private-sdtd-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://gitlab.com/Gh-Badr/weather-forecast/
  password: glpat-CDKauszwPZ64xsEmty4e
  username: Hamdane10