version: "2"
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"
  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    healthcheck:
      test: ["CMD-SHELL", "nc -z kafka 9092"]
      interval: 3s
      timeout: 3s
      retries: 10

# For testing purposes, we'll add the producer and consumer to the same docker-compose file.
  database:
    image: mongo
    restart: "no"
    ports:
      - "27017:27017"  
    
  producer:
    image: hamdaneyassine/producer
    restart: "no"
    environment:
      API_URL: https://api.openweathermap.org/data/2.5
      WEATHER_API_KEY: 6830074118b9aa4742c6f006e4381ab6
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy

  consumer:
    image: hamdaneyassine/consumer
    restart: "no"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MONGODB_URL: mongodb://database:27017
      MONGODB_DB_NAME: weather
      MONGODB_COLLECTION: cities
    depends_on:
      kafka:
        condition: service_healthy
      database:
        condition: service_started

  backend:
    image: hamdaneyassine/backend
    restart: "no"
    environment:
      MONGODB_URL: mongodb://database:27017
      MONGODB_DB_NAME: weather
      MONGODB_COLLECTION: cities
      RAPIDAPI_KEY: 5ae73cb8ebmsh20d8f730b6a5913p13dde8jsnaa3fe43ff7ac
      GEOAPI_BASE_URL: https://wft-geo-db.p.rapidapi.com/v1/geo/cities
      HOST: localhost
      PORT: 3001
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
      consumer:
        condition: service_started
      producer:
        condition: service_started
      database:
        condition: service_started

  frontend:
    image: hamdaneyassine/frontend
    restart: "no"
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://backend:3001
    depends_on:
      backend:
        condition: service_started