stages:
  - build

.build_template: &build_template
  stage: build
  image: docker:24.0.7-cli
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_TAG: ${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
    DOCKER_BUILD_ARGS: ""
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS 
  script:
    - docker build $DOCKER_BUILD_ARGS -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG