---

# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: sdtd-project
data:
  HOST: "0.0.0.0"
  PORT: "3001"
  KAFKA_NUM_PARTITIONS: "2"

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sdtd-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: check-kafka
        image: busybox:1.28
        command:
        - sh
        - -c
        - until nslookup kafka; do echo waiting for kafka; sleep 2; done
      - name: check-database
        image: busybox:1.28
        command:
        - sh
        - -c
        - until nslookup database; do echo waiting for database; sleep 2; done
      containers:
      - name: backend
        image: ghbadr/backend:efb4e439
        ports:
        - containerPort: 3001
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        env:
        - name: MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: MONGODB_URL
        - name: MONGODB_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: MONGODB_DB_NAME
        - name: MONGODB_COLLECTION
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: MONGODB_COLLECTION
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: PORT
        - name: KAFKA_NUM_PARTITIONS
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: KAFKA_NUM_PARTITIONS

---

# Service
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: sdtd-project
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: backend

---
# NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
  namespace: sdtd-project
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: backend