# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: sdtd-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: hamdaneyassine/consumer
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: MONGODB_URL
        - name: MONGODB_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: MONGODB_DB_NAME
        - name: MONGODB_COLLECTION
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: MONGODB_COLLECTION

---

# Service
apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: sdtd-project
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: consumer