apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-cleaner
  namespace: sdtd-project
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: db-cleaner
            image: ghbadr/database-cleaner:14150682
            env:
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: MONGODB_URL
            - name: MONGODB_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: MONGODB_DB_NAME
            - name: MONGODB_COLLECTION
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: MONGODB_COLLECTION
          restartPolicy: OnFailure