apiVersion: v1
kind: ConfigMap
metadata:
  name: kafdrop-config
  namespace: sdtd-project
data:
  KAFKA_BROKERCONNECT: "kafka:29092"

---
# ConfigMaps
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: sdtd-project
data:
  KAFKA_BROKERCONNECT: "kafka:29092"
  KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
  KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
  KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
  KAFKA_RESTART_ATTEMPTS: "10"
  KAFKA_RESTART_DELAY: "5"
  ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: sdtd-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: obsidiandynamics/kafka
        ports:
        - containerPort: 9092
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - nc -z localhost 9092
          initialDelaySeconds: 15
          periodSeconds: 3
          timeoutSeconds: 3
          failureThreshold: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - nc -z localhost 9092
          initialDelaySeconds: 5
          periodSeconds: 3
          timeoutSeconds: 3
          failureThreshold: 10
        env:
        - name: KAFKA_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_LISTENERS
        - name: KAFKA_ADVERTISED_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_ADVERTISED_LISTENERS
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_INTER_BROKER_LISTENER_NAME
        - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_ZOOKEEPER_SESSION_TIMEOUT
        - name: KAFKA_RESTART_ATTEMPTS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_RESTART_ATTEMPTS
        - name: KAFKA_RESTART_DELAY
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_RESTART_DELAY
        - name: ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: sdtd-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
      - name: kafdrop
        image: obsidiandynamics/kafdrop
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: kafdrop-config

---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: sdtd-project
spec:
  type: NodePort
  ports:
  - port: 9000
  selector:
    app: kafdrop
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: sdtd-project
spec:
  type: ClusterIP
  ports:
  - port: 9092
  selector:
    app: kafka