# Secret
apiVersion: v1
kind: Secret
metadata:
  name: producer-secret
  namespace: sdtd-project
type: Opaque
data:
  WEATHER_API_KEY: NjgzMDA3NDExOGI5YWE0NzQyYzZmMDA2ZTQzODFhYjY=

---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
  namespace: sdtd-project
data:
  API_URL: https://api.openweathermap.org/data/2.5
  PRODUCER_MONGODB_COLLECTION: pendingCities

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: sdtd-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      initContainers:
      - name: check-kafka
        image: busybox:1.28
        command:
        - sh
        - -c
        - until nslookup kafka; do echo waiting for kafka; sleep 2; done
      containers:
      - name: producer
        image: hamdaneyassine/producer:v5.0
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - ps aux | grep python || exit 1
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - ps aux | grep python || exit 1
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: producer-config
              key: API_URL
        - name: PRODUCER_MONGODB_COLLECTION
          valueFrom:
            configMapKeyRef:
              name: producer-config
              key: PRODUCER_MONGODB_COLLECTION
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_BOOTSTRAP_SERVERS
        - name: WEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: producer-secret
              key: WEATHER_API_KEY
        - name: MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: MONGODB_URL
        - name: MONGODB_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: MONGODB_DB_NAME